export default function Terms() {
  return (
    <div className="min-h-screen bg-[#F6F4EE] py-16 px-6">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg p-8">
        <h1 className="font-['Poppins'] font-bold text-4xl text-[#1C2E25] mb-8">Terms of Service</h1>
        
        <section className="mb-8">
          <h2 className="font-['Poppins'] font-semibold text-2xl text-[#315E47] mb-4">Paid Features and AI Scanner Terms</h2>
          
          <h3 className="font-['Poppins'] font-semibold text-xl text-[#1C2E25] mb-3 mt-6">1. Paid Access and Scope</h3>
          <p className="font-['Open_Sans'] text-[#1C2E25] mb-4 leading-relaxed">
            ReFURRM offers certain advanced tools, including the AI Unit Scanner and AI Item Scanner, exclusively to paid subscribers under the Pro tier. These tools are designed to estimate the approximate resale value of non-personal items visible in user-submitted or publicly available storage unit photos.
          </p>

          <h3 className="font-['Poppins'] font-semibold text-xl text-[#1C2E25] mb-3 mt-6">2. Limited Use and Purpose</h3>
          <p className="font-['Open_Sans'] text-[#1C2E25] mb-4 leading-relaxed">
            The AI Scanner tools are provided solely for informational purposes to assist users in evaluating the potential resale value of visible, physical goods such as furniture, appliances, or equipment. They must not be used to analyze, identify, or assign value to personal or sentimental property, private images, or any material that could contain personally identifiable information.
          </p>

          <h3 className="font-['Poppins'] font-semibold text-xl text-[#1C2E25] mb-3 mt-6">3. Accuracy and Liability Disclaimer</h3>
          <p className="font-['Open_Sans'] text-[#1C2E25] mb-4 leading-relaxed">
            ReFURRM does not guarantee the accuracy, completeness, or reliability of any valuation generated by the AI Scanner. Estimated resale values are algorithmic projections derived from available market data and may not reflect actual sale prices. Users acknowledge that they rely on these tools at their own discretion and risk.
          </p>

          <h3 className="font-['Poppins'] font-semibold text-xl text-[#1C2E25] mb-3 mt-6">4. Ethical and Legal Compliance</h3>
          <p className="font-['Open_Sans'] text-[#1C2E25] mb-4 leading-relaxed">
            By accessing and using paid features, users agree to comply with all applicable laws and ReFURRM's ethical use standards. ReFURRM reserves the right to suspend or revoke access to any paid feature if a user attempts to upload personal, confidential, or inappropriate content, or misuses the AI Scanner outside of its intended valuation purpose.
          </p>

          <h3 className="font-['Poppins'] font-semibold text-xl text-[#1C2E25] mb-3 mt-6">5. Non-Refundable Digital Services</h3>
          <p className="font-['Open_Sans'] text-[#1C2E25] mb-4 leading-relaxed">
            Fees paid for Pro or subscription access cover digital services and platform maintenance. All payments are non-refundable, except where required by law or at ReFURRM's sole discretion in the event of a verified technical failure.
          </p>
        </section>

        <p className="font-['Open_Sans'] text-sm text-[#C8BFAE] mt-12">Last Updated: November 2025</p>
      </div>
    </div>
  );
}
