export const rescueStories = [
  {
    id: '1',
    title: "Martinez Family Heirlooms Recovered",
    familyName: "The Martinez Family",
    location: "Phoenix, AZ",
    date: "October 2025",
    beforeImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491016451_651be9ca.webp",
    afterImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491021550_5c3a41e1.webp",
    testimonial: "We thought my grandmother's photo albums and jewelry were lost forever. ReFURRM found them and brought our family history back to us.",
    itemsRecovered: 347,
    donationAmount: 2850,
    status: 'completed' as const,
    fullStory: "When Sarah Martinez lost her job during the pandemic, she fell behind on her storage unit payments. Inside were three generations of family photos, her grandmother's wedding ring, and irreplaceable documents.\n\nReFURRM's team spent two days carefully sorting through the unit. Using AI-assisted identification, they located 347 personal items including the photo albums Sarah thought were gone forever.\n\nToday, Sarah has her family's history back and has started a new job. She volunteers with ReFURRM to help other families in similar situations.",
    donorNames: ["Anonymous", "John D.", "Maria S.", "ReFURRM Foundation"],
    rescueId: 'rescue_001'
  },
  {
    id: '2',
    title: "Children's Memories Saved",
    familyName: "The Wilson Family",
    location: "Dallas, TX",
    date: "September 2025",
    beforeImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491018328_253b2f1a.webp",
    afterImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491023582_c15f965a.webp",
    testimonial: "My kids' baby books, first drawings, and birthday videos were all in that unit. I cried when ReFURRM called to say they found everything.",
    itemsRecovered: 189,
    donationAmount: 1950,
    status: 'completed' as const,
    fullStory: "James Wilson's storage unit contained his children's entire early childhood - baby books, artwork, videos of first steps, and birthday celebrations. After a divorce and job loss, he couldn't keep up with payments.\n\nReFURRM volunteers worked with the storage facility to rescue the unit before auction. Every item was carefully cataloged and preserved.\n\nJames now has stable housing and his children have their memories back. The family donated $500 back to ReFURRM to help the next family.",
    donorNames: ["Sarah M.", "Anonymous", "Tech Workers United"],
    rescueId: 'rescue_002'
  },
  {
    id: '3',
    title: "Veteran's Service Records Restored",
    familyName: "The Thompson Family",
    location: "Austin, TX",
    date: "August 2025",
    beforeImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491020326_1441aee4.webp",
    afterImage: "https://d64gsuwffb70l.cloudfront.net/690c55f62a1c1509e277d961_1762491025359_2e1a17a7.webp",
    testimonial: "My father's military medals, discharge papers, and war letters were everything to our family. ReFURRM gave us back our hero's legacy.",
    itemsRecovered: 156,
    donationAmount: 3200,
    status: 'completed' as const,
    fullStory: "Robert Thompson's father served in Vietnam. When Robert faced medical bankruptcy, his storage unit with his father's military memorabilia was at risk.\n\nReFURRM prioritized this rescue due to the historical significance. The team found medals, letters home, photographs, and official service records - all carefully preserved.\n\nThe family has since donated the collection to a military museum, where Robert's father's story will be preserved for future generations.",
    donorNames: ["Veterans Fund", "Anonymous", "Linda K.", "Michael R."],
    rescueId: 'rescue_003'
  }
];
